### ISSUE TITLE
in-place import

### ISSUE THREAD

**Issue by pwalczysko** [ome/devspace#214]
When I exec into the server container, I cannot see the ``/uod/idr...`` mount from there, i.e. cannot import in-place.
```
[root@idr1-slot2 pwalczysko]# docker exec  -it merge-ci-omero-1 bash
bash-5.1$ ls /
afs  bin  dev  etc  home  lib  lib64  lost+found  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
```

When I try to perform the workflow from ``idr1-slot2`` directly, I get

```
omero import --transfer=ln_s -T Dataset:name:CDK5RAP2-C /uod/idr/filesets/idr0021-lawo-pericentriolarmaterial/Raw-files/CDK5RAP2-C/
....
Check failed: /home/omero/omero-server-data/ManagedRepository/user-3_52/Blitz-0-Ice.ThreadPool.Server-17/2024-03/21/11-33-16.477/Cep215_PCNT_gtub_20110506_Fri-1726_0_SIR_PRJ.dv cannot be modified locally!
You likely do not have access to the ManagedRepository for in-place import.
Aborting...
---------------------------------------------------

	at ome.formats.importer.transfers.AbstractExecFileTransfer.failLocationCheck(AbstractExecFileTransfer.java:150)
	at ome.formats.importer.transfers.AbstractExecFileTransfer.checkLocation(AbstractExecFileTransfer.java:132)
	at ome.formats.importer.transfers.AbstractExecFileTransfer.transfer(AbstractExecFileTransfer.java:63)
	at ome.formats.importer.ImportLibrary.uploadFile(ImportLibrary.java:531)
	at ome.formats.importer.ImportLibrary$3.call(ImportLibrary.java:634)
	at ome.formats.importer.ImportLibrary$3.call(ImportLibrary.java:631)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2024-03-21 11:33:17,368 6750       [2-thread-1] ERROR        ome.formats.importer.ImportLibrary - Error on import
java.lang.RuntimeException: 
---------------------------------------------------
Check failed: /home/omero/omero-server-data/ManagedRepository/user-3_52/Blitz-0-Ice.ThreadPool.Server-17/2024-03/21/11-33-16.477/Cep215_PCNT_gtub_20110506_Fri-1726_0_SIR_PRJ.dv cannot be modified locally!
You likely do not have access to the ManagedRepository for in-place import.
Aborting...
```

cc @jburel @sbesson

**Comment by pwalczysko** [comment]
I think we need to add the ``/uod/idr`` as a volume to the container...

**Comment by jburel** [comment]
see https://github.com/ome/devspace/pull/215
